### ISSUE TITLE
Sẽ tốt hơn nếu nó là 1 bản extensions

### ISSUE THREAD

**Issue by joehua87** [lamhieu-vk/ciser#1]
Em tham khảo những project lớn, nó để những cái lõi (cái tối thiểu) trong 1 project. 
Những cái nó làm thêm - chỉ sử dụng trong những trường hợp đặc thù thì sẽ tách ra 1 package riêng. 
Xem ví dụ tại https://github.com/babel/babel/tree/master/packages. Bản thân tachyons nó cũng làm vậy. https://github.com/tachyons-css/tachyons-flexbox
Như vậy sẽ có những ưu điểm sau:
* Lightweight (tạm dịch là nhẹ)
* Người dùng sẽ dễ chấp nhận nó hơn, không ai bỏ 1 thư viện mà ng ta đã quen thuộc để theo 1 bản folk, trừ những trường hợp Owner không maintain nữa
* Dễ dàng phát triển song song
* **Tôn trọng người viết trước đó**, đồng thời tăng giá trị cho bản thân. E thử nghĩ trường hợp e viết 1 project có khoảng 5k người star sử dụng đi. Có 1 ku A nào folk ra, thêm 1 vài cái rồi đổi tên lại. E thử xem những cảm nghĩ của những người sau:
  - Thằng viết project (em) nghĩ gì về ku A
  - Cộng đồng người dùng nghĩ gì về ku A

**Comment by lh0x00** [comment]
lúc đầu em cũng định chỉ làm nó là 1 bản ext thôi nhưng sau em quyết định nâng cấp nó, là một bản riêng không lệ thuộc kể từ bản forked tachyons (v4.8.1).
để thể hiện sự tôn trong tác giả thì những mẫu nào em không nâng cấp em vẫn sẽ để ghi chú của tachyons, không thay đổi.
