### ISSUE TITLE
Sizes - typos in readme + vmin + missing examples for f[x]s

### ISSUE THREAD

**Issue by MartinKavik** [lamhieu-vk/ciser#2]
Hi!

1. There are some typos in **Readme**:
```
.min-vh/w-[25 | 50 | 75 | 100]
.min-vh/w-[25 | 50 | 75 | 100]  // should be max
````
And extra bracket after `.p/m`:
```
.p][x]s
.m][x]s
```

2. Is there somewhere function with css `vmin`? (Or do you have some reasons why it shouldn't be there?)

3.  Could you please write some use case for e.g. `.w[x]s = w[x+1] - (w[x+1] - w[x]) / 2`? Or add link to demo or image with example of using **\*\*s** functions?

---

Other questions:

4. Is there a roadmap / "wish board" of what you want to implement?

5. I'm using Tachyons with **Elm** and I am a contributor in http://package.elm-lang.org/packages/justgage/tachyons-elm/latest, so I can create Elm package for **ciser** in the future.

6. What is *ciser*?

Nice repo!

**Comment by lh0x00** [comment]
@MartinKavik the first, thanks because opend issue
I apologize that during the development process I did not see the new issue that you sent to me. Thanks for your suggestions, I will fix it soon!
- 1. fixed at https://github.com/lamhieu-vk/ciser/commit/4d50e043e1ae48f05c68ed197a575b9439a537ba
- 2. Can you tell more about it?
- 3. I am in the process of making a page about ciser, there are examples.
- 4. I will update it soon! thank you 👍 
- 5. thank you for trusting it, you can use version 2.2.4 for your project! I will inform you when the latest information is available.
- 6. I like it 👍  hehee ^^

**Comment by MartinKavik** [comment]
@lamhieu-vk Thanks for answers!
- **ii.** - `vmin` is quite useful mainly for responsive typography (http://thenewcode.com/1137/MinMaxing-Understanding-vMin-and-vMax-in-CSS), but for typography is also useful `calc` (see https://zellwk.com/blog/viewport-based-typography/)

  - I think you are more experienced with CSS than me, so it's quite possible you see problems with these properties or you know better solutions

- **v.** - super! It's possible that I'll try to use it on some bigger project next year.  In this case, I'll contribute more to this repo (feedbacks, PR..)

**Comment by lh0x00** [comment]
@MartinKavik 
- 2. i will research and decided to upgrade it in the shortest time possible.
- 5. thank you for using it, I actually noticed the lack of tachoyns so I upgraded it to own development (apply for the product I'm using) so you keep quiet use, every I forgot to open open issue in there.

**Comment by MartinKavik** [comment]
@lamhieu-vk 
> iii. I am in the process of making a page about ciser, there are examples.

This script: https://github.com/justgage/tachyons-elm/blob/3.1.1/scripts/convert.js transforms **tachyons.css** to **Elm** classes and I'll adapt it for **ciser**.
I can modify it to transform **ciser's** classes to other objects - I think it can be useful for autogenerating `/docs/*` or some lists/guides/search data on the page about **ciser**.

If you are interested in it, just create a new issue and we can discuss it there.

**Comment by lh0x00** [comment]
is this what you need? [liser](https://github.com/lamhieu-vk/liser), I created it to build css modules, you can append more module and file it easier with liser.
